/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UltraMarathonsRouteImport } from './routes/ultra-marathons'
import { Route as TrailRunningEventsRouteImport } from './routes/trail-running-events'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RunningEventsThisWeekendRouteImport } from './routes/running-events-this-weekend'
import { Route as RunningEventsNextWeekendRouteImport } from './routes/running-events-next-weekend'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RoadRacesRouteImport } from './routes/road-races'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MultiTerrainRacesRouteImport } from './routes/multi-terrain-races'
import { Route as MarathonsRouteImport } from './routes/marathons'
import { Route as ListYourEventRouteImport } from './routes/list-your-event'
import { Route as JuniorParkrunEventsRouteImport } from './routes/junior-parkrun-events'
import { Route as IndexDothtmlRouteImport } from './routes/index[.]html'
import { Route as HalfMarathonsRouteImport } from './routes/half-marathons'
import { Route as FellRacesRouteImport } from './routes/fell-races'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminShellRouteImport } from './routes/_adminShell'
import { Route as R5kRacesRouteImport } from './routes/5k-races'
import { Route as R10kRacesRouteImport } from './routes/10k-races'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunningClubsIndexRouteImport } from './routes/running-clubs.index'
import { Route as ParkrunEventsIndexRouteImport } from './routes/parkrun-events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UltraMarathonsMonthRouteImport } from './routes/ultra-marathons.$month'
import { Route as RunningEventsSlugRouteImport } from './routes/running-events.$slug'
import { Route as RunningClubsSlugRouteImport } from './routes/running-clubs.$slug'
import { Route as ParkrunEventsSlugRouteImport } from './routes/parkrun-events.$slug'
import { Route as MarathonsMonthRouteImport } from './routes/marathons.$month'
import { Route as HalfMarathonsMonthRouteImport } from './routes/half-marathons.$month'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as R5kRacesMonthRouteImport } from './routes/5k-races.$month'
import { Route as R10kRacesMonthRouteImport } from './routes/10k-races.$month'
import { Route as RunningEventsSlugDistanceRouteImport } from './routes/running-events.$slug_.$distance'
import { Route as RunningClubsSlugClaimRouteImport } from './routes/running-clubs.$slug.claim'
import { Route as ParkrunEventsRegionRegionRouteImport } from './routes/parkrun-events.region.$region'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicTrackSearchClickRouteImport } from './routes/api/public/track-search-click'
import { Route as ApiPublicTrackSearchRouteImport } from './routes/api/public/track-search'
import { Route as ApiPublicImportEventsRouteImport } from './routes/api/public/import-events'
import { Route as ApiPublicImportClubsRouteImport } from './routes/api/public/import-clubs'
import { Route as AdminShellAdminSyncRunsRouteImport } from './routes/_adminShell.admin.sync-runs'
import { Route as AdminShellAdminSearchRouteImport } from './routes/_adminShell.admin.search'
import { Route as AdminShellAdminClubClaimsRouteImport } from './routes/_adminShell.admin.club-claims'
import { Route as AdminShellAdminClaimsRouteImport } from './routes/_adminShell.admin.claims'
import { Route as AdminShellAdminEventsIndexRouteImport } from './routes/_adminShell.admin.events.index'
import { Route as AdminShellAdminClubsIndexRouteImport } from './routes/_adminShell.admin.clubs.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksSendRaceRemindersRouteImport } from './routes/api/public/hooks/send-race-reminders'
import { Route as ApiPublicAdminSyncScottishAthleticsClubsRouteImport } from './routes/api/public/admin/sync-scottish-athletics-clubs'
import { Route as ApiPublicAdminSyncScottishAthleticsRouteImport } from './routes/api/public/admin/sync-scottish-athletics'
import { Route as ApiPublicAdminSyncEnglandAthleticsRouteImport } from './routes/api/public/admin/sync-england-athletics'
import { Route as ApiPublicAdminFixEventUrlsRouteImport } from './routes/api/public/admin/fix-event-urls'
import { Route as AdminShellAdminEventsEnrichDatesRouteImport } from './routes/_adminShell.admin.events.enrich-dates'
import { Route as AdminShellAdminEventsDuplicatesRouteImport } from './routes/_adminShell.admin.events.duplicates'
import { Route as AdminShellAdminEventsIdRouteImport } from './routes/_adminShell.admin.events.$id'
import { Route as AdminShellAdminClubsNewRouteImport } from './routes/_adminShell.admin.clubs.new'
import { Route as AdminShellAdminClubsIdRouteImport } from './routes/_adminShell.admin.clubs.$id'

const UltraMarathonsRoute = UltraMarathonsRouteImport.update({
  id: '/ultra-marathons',
  path: '/ultra-marathons',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailRunningEventsRoute = TrailRunningEventsRouteImport.update({
  id: '/trail-running-events',
  path: '/trail-running-events',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningEventsThisWeekendRoute =
  RunningEventsThisWeekendRouteImport.update({
    id: '/running-events-this-weekend',
    path: '/running-events-this-weekend',
    getParentRoute: () => rootRouteImport,
  } as any)
const RunningEventsNextWeekendRoute =
  RunningEventsNextWeekendRouteImport.update({
    id: '/running-events-next-weekend',
    path: '/running-events-next-weekend',
    getParentRoute: () => rootRouteImport,
  } as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadRacesRoute = RoadRacesRouteImport.update({
  id: '/road-races',
  path: '/road-races',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiTerrainRacesRoute = MultiTerrainRacesRouteImport.update({
  id: '/multi-terrain-races',
  path: '/multi-terrain-races',
  getParentRoute: () => rootRouteImport,
} as any)
const MarathonsRoute = MarathonsRouteImport.update({
  id: '/marathons',
  path: '/marathons',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourEventRoute = ListYourEventRouteImport.update({
  id: '/list-your-event',
  path: '/list-your-event',
  getParentRoute: () => rootRouteImport,
} as any)
const JuniorParkrunEventsRoute = JuniorParkrunEventsRouteImport.update({
  id: '/junior-parkrun-events',
  path: '/junior-parkrun-events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDothtmlRoute = IndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const HalfMarathonsRoute = HalfMarathonsRouteImport.update({
  id: '/half-marathons',
  path: '/half-marathons',
  getParentRoute: () => rootRouteImport,
} as any)
const FellRacesRoute = FellRacesRouteImport.update({
  id: '/fell-races',
  path: '/fell-races',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/_adminShell',
  getParentRoute: () => rootRouteImport,
} as any)
const R5kRacesRoute = R5kRacesRouteImport.update({
  id: '/5k-races',
  path: '/5k-races',
  getParentRoute: () => rootRouteImport,
} as any)
const R10kRacesRoute = R10kRacesRouteImport.update({
  id: '/10k-races',
  path: '/10k-races',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningClubsIndexRoute = RunningClubsIndexRouteImport.update({
  id: '/running-clubs/',
  path: '/running-clubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkrunEventsIndexRoute = ParkrunEventsIndexRouteImport.update({
  id: '/parkrun-events/',
  path: '/parkrun-events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const UltraMarathonsMonthRoute = UltraMarathonsMonthRouteImport.update({
  id: '/$month',
  path: '/$month',
  getParentRoute: () => UltraMarathonsRoute,
} as any)
const RunningEventsSlugRoute = RunningEventsSlugRouteImport.update({
  id: '/running-events/$slug',
  path: '/running-events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningClubsSlugRoute = RunningClubsSlugRouteImport.update({
  id: '/running-clubs/$slug',
  path: '/running-clubs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkrunEventsSlugRoute = ParkrunEventsSlugRouteImport.update({
  id: '/parkrun-events/$slug',
  path: '/parkrun-events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MarathonsMonthRoute = MarathonsMonthRouteImport.update({
  id: '/$month',
  path: '/$month',
  getParentRoute: () => MarathonsRoute,
} as any)
const HalfMarathonsMonthRoute = HalfMarathonsMonthRouteImport.update({
  id: '/$month',
  path: '/$month',
  getParentRoute: () => HalfMarathonsRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R5kRacesMonthRoute = R5kRacesMonthRouteImport.update({
  id: '/$month',
  path: '/$month',
  getParentRoute: () => R5kRacesRoute,
} as any)
const R10kRacesMonthRoute = R10kRacesMonthRouteImport.update({
  id: '/$month',
  path: '/$month',
  getParentRoute: () => R10kRacesRoute,
} as any)
const RunningEventsSlugDistanceRoute =
  RunningEventsSlugDistanceRouteImport.update({
    id: '/running-events/$slug_/$distance',
    path: '/running-events/$slug/$distance',
    getParentRoute: () => rootRouteImport,
  } as any)
const RunningClubsSlugClaimRoute = RunningClubsSlugClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => RunningClubsSlugRoute,
} as any)
const ParkrunEventsRegionRegionRoute =
  ParkrunEventsRegionRegionRouteImport.update({
    id: '/parkrun-events/region/$region',
    path: '/parkrun-events/region/$region',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackSearchClickRoute =
  ApiPublicTrackSearchClickRouteImport.update({
    id: '/api/public/track-search-click',
    path: '/api/public/track-search-click',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackSearchRoute = ApiPublicTrackSearchRouteImport.update({
  id: '/api/public/track-search',
  path: '/api/public/track-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImportEventsRoute = ApiPublicImportEventsRouteImport.update({
  id: '/api/public/import-events',
  path: '/api/public/import-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImportClubsRoute = ApiPublicImportClubsRouteImport.update({
  id: '/api/public/import-clubs',
  path: '/api/public/import-clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellAdminSyncRunsRoute = AdminShellAdminSyncRunsRouteImport.update({
  id: '/admin/sync-runs',
  path: '/admin/sync-runs',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAdminSearchRoute = AdminShellAdminSearchRouteImport.update({
  id: '/admin/search',
  path: '/admin/search',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAdminClubClaimsRoute =
  AdminShellAdminClubClaimsRouteImport.update({
    id: '/admin/club-claims',
    path: '/admin/club-claims',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellAdminClaimsRoute = AdminShellAdminClaimsRouteImport.update({
  id: '/admin/claims',
  path: '/admin/claims',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAdminEventsIndexRoute =
  AdminShellAdminEventsIndexRouteImport.update({
    id: '/admin/events/',
    path: '/admin/events/',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellAdminClubsIndexRoute =
  AdminShellAdminClubsIndexRouteImport.update({
    id: '/admin/clubs/',
    path: '/admin/clubs/',
    getParentRoute: () => AdminShellRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendRaceRemindersRoute =
  ApiPublicHooksSendRaceRemindersRouteImport.update({
    id: '/api/public/hooks/send-race-reminders',
    path: '/api/public/hooks/send-race-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSyncScottishAthleticsClubsRoute =
  ApiPublicAdminSyncScottishAthleticsClubsRouteImport.update({
    id: '/api/public/admin/sync-scottish-athletics-clubs',
    path: '/api/public/admin/sync-scottish-athletics-clubs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSyncScottishAthleticsRoute =
  ApiPublicAdminSyncScottishAthleticsRouteImport.update({
    id: '/api/public/admin/sync-scottish-athletics',
    path: '/api/public/admin/sync-scottish-athletics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSyncEnglandAthleticsRoute =
  ApiPublicAdminSyncEnglandAthleticsRouteImport.update({
    id: '/api/public/admin/sync-england-athletics',
    path: '/api/public/admin/sync-england-athletics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminFixEventUrlsRoute =
  ApiPublicAdminFixEventUrlsRouteImport.update({
    id: '/api/public/admin/fix-event-urls',
    path: '/api/public/admin/fix-event-urls',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminShellAdminEventsEnrichDatesRoute =
  AdminShellAdminEventsEnrichDatesRouteImport.update({
    id: '/admin/events/enrich-dates',
    path: '/admin/events/enrich-dates',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellAdminEventsDuplicatesRoute =
  AdminShellAdminEventsDuplicatesRouteImport.update({
    id: '/admin/events/duplicates',
    path: '/admin/events/duplicates',
    getParentRoute: () => AdminShellRoute,
  } as any)
const AdminShellAdminEventsIdRoute = AdminShellAdminEventsIdRouteImport.update({
  id: '/admin/events/$id',
  path: '/admin/events/$id',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAdminClubsNewRoute = AdminShellAdminClubsNewRouteImport.update({
  id: '/admin/clubs/new',
  path: '/admin/clubs/new',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAdminClubsIdRoute = AdminShellAdminClubsIdRouteImport.update({
  id: '/admin/clubs/$id',
  path: '/admin/clubs/$id',
  getParentRoute: () => AdminShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/10k-races': typeof R10kRacesRouteWithChildren
  '/5k-races': typeof R5kRacesRouteWithChildren
  '/about': typeof AboutRoute
  '/fell-races': typeof FellRacesRoute
  '/half-marathons': typeof HalfMarathonsRouteWithChildren
  '/index.html': typeof IndexDothtmlRoute
  '/junior-parkrun-events': typeof JuniorParkrunEventsRoute
  '/list-your-event': typeof ListYourEventRoute
  '/marathons': typeof MarathonsRouteWithChildren
  '/multi-terrain-races': typeof MultiTerrainRacesRoute
  '/privacy': typeof PrivacyRoute
  '/road-races': typeof RoadRacesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/running-events-next-weekend': typeof RunningEventsNextWeekendRoute
  '/running-events-this-weekend': typeof RunningEventsThisWeekendRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trail-running-events': typeof TrailRunningEventsRoute
  '/ultra-marathons': typeof UltraMarathonsRouteWithChildren
  '/10k-races/$month': typeof R10kRacesMonthRoute
  '/5k-races/$month': typeof R5kRacesMonthRoute
  '/admin/login': typeof AdminLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/half-marathons/$month': typeof HalfMarathonsMonthRoute
  '/marathons/$month': typeof MarathonsMonthRoute
  '/parkrun-events/$slug': typeof ParkrunEventsSlugRoute
  '/running-clubs/$slug': typeof RunningClubsSlugRouteWithChildren
  '/running-events/$slug': typeof RunningEventsSlugRoute
  '/ultra-marathons/$month': typeof UltraMarathonsMonthRoute
  '/admin/': typeof AdminIndexRoute
  '/parkrun-events/': typeof ParkrunEventsIndexRoute
  '/running-clubs/': typeof RunningClubsIndexRoute
  '/admin/claims': typeof AdminShellAdminClaimsRoute
  '/admin/club-claims': typeof AdminShellAdminClubClaimsRoute
  '/admin/search': typeof AdminShellAdminSearchRoute
  '/admin/sync-runs': typeof AdminShellAdminSyncRunsRoute
  '/api/public/import-clubs': typeof ApiPublicImportClubsRoute
  '/api/public/import-events': typeof ApiPublicImportEventsRoute
  '/api/public/track-search': typeof ApiPublicTrackSearchRoute
  '/api/public/track-search-click': typeof ApiPublicTrackSearchClickRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/parkrun-events/region/$region': typeof ParkrunEventsRegionRegionRoute
  '/running-clubs/$slug/claim': typeof RunningClubsSlugClaimRoute
  '/running-events/$slug/$distance': typeof RunningEventsSlugDistanceRoute
  '/admin/clubs/$id': typeof AdminShellAdminClubsIdRoute
  '/admin/clubs/new': typeof AdminShellAdminClubsNewRoute
  '/admin/events/$id': typeof AdminShellAdminEventsIdRoute
  '/admin/events/duplicates': typeof AdminShellAdminEventsDuplicatesRoute
  '/admin/events/enrich-dates': typeof AdminShellAdminEventsEnrichDatesRoute
  '/api/public/admin/fix-event-urls': typeof ApiPublicAdminFixEventUrlsRoute
  '/api/public/admin/sync-england-athletics': typeof ApiPublicAdminSyncEnglandAthleticsRoute
  '/api/public/admin/sync-scottish-athletics': typeof ApiPublicAdminSyncScottishAthleticsRoute
  '/api/public/admin/sync-scottish-athletics-clubs': typeof ApiPublicAdminSyncScottishAthleticsClubsRoute
  '/api/public/hooks/send-race-reminders': typeof ApiPublicHooksSendRaceRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/clubs/': typeof AdminShellAdminClubsIndexRoute
  '/admin/events/': typeof AdminShellAdminEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/10k-races': typeof R10kRacesRouteWithChildren
  '/5k-races': typeof R5kRacesRouteWithChildren
  '/about': typeof AboutRoute
  '/fell-races': typeof FellRacesRoute
  '/half-marathons': typeof HalfMarathonsRouteWithChildren
  '/index.html': typeof IndexDothtmlRoute
  '/junior-parkrun-events': typeof JuniorParkrunEventsRoute
  '/list-your-event': typeof ListYourEventRoute
  '/marathons': typeof MarathonsRouteWithChildren
  '/multi-terrain-races': typeof MultiTerrainRacesRoute
  '/privacy': typeof PrivacyRoute
  '/road-races': typeof RoadRacesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/running-events-next-weekend': typeof RunningEventsNextWeekendRoute
  '/running-events-this-weekend': typeof RunningEventsThisWeekendRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trail-running-events': typeof TrailRunningEventsRoute
  '/ultra-marathons': typeof UltraMarathonsRouteWithChildren
  '/10k-races/$month': typeof R10kRacesMonthRoute
  '/5k-races/$month': typeof R5kRacesMonthRoute
  '/admin/login': typeof AdminLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/half-marathons/$month': typeof HalfMarathonsMonthRoute
  '/marathons/$month': typeof MarathonsMonthRoute
  '/parkrun-events/$slug': typeof ParkrunEventsSlugRoute
  '/running-clubs/$slug': typeof RunningClubsSlugRouteWithChildren
  '/running-events/$slug': typeof RunningEventsSlugRoute
  '/ultra-marathons/$month': typeof UltraMarathonsMonthRoute
  '/admin': typeof AdminIndexRoute
  '/parkrun-events': typeof ParkrunEventsIndexRoute
  '/running-clubs': typeof RunningClubsIndexRoute
  '/admin/claims': typeof AdminShellAdminClaimsRoute
  '/admin/club-claims': typeof AdminShellAdminClubClaimsRoute
  '/admin/search': typeof AdminShellAdminSearchRoute
  '/admin/sync-runs': typeof AdminShellAdminSyncRunsRoute
  '/api/public/import-clubs': typeof ApiPublicImportClubsRoute
  '/api/public/import-events': typeof ApiPublicImportEventsRoute
  '/api/public/track-search': typeof ApiPublicTrackSearchRoute
  '/api/public/track-search-click': typeof ApiPublicTrackSearchClickRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/parkrun-events/region/$region': typeof ParkrunEventsRegionRegionRoute
  '/running-clubs/$slug/claim': typeof RunningClubsSlugClaimRoute
  '/running-events/$slug/$distance': typeof RunningEventsSlugDistanceRoute
  '/admin/clubs/$id': typeof AdminShellAdminClubsIdRoute
  '/admin/clubs/new': typeof AdminShellAdminClubsNewRoute
  '/admin/events/$id': typeof AdminShellAdminEventsIdRoute
  '/admin/events/duplicates': typeof AdminShellAdminEventsDuplicatesRoute
  '/admin/events/enrich-dates': typeof AdminShellAdminEventsEnrichDatesRoute
  '/api/public/admin/fix-event-urls': typeof ApiPublicAdminFixEventUrlsRoute
  '/api/public/admin/sync-england-athletics': typeof ApiPublicAdminSyncEnglandAthleticsRoute
  '/api/public/admin/sync-scottish-athletics': typeof ApiPublicAdminSyncScottishAthleticsRoute
  '/api/public/admin/sync-scottish-athletics-clubs': typeof ApiPublicAdminSyncScottishAthleticsClubsRoute
  '/api/public/hooks/send-race-reminders': typeof ApiPublicHooksSendRaceRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/clubs': typeof AdminShellAdminClubsIndexRoute
  '/admin/events': typeof AdminShellAdminEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/10k-races': typeof R10kRacesRouteWithChildren
  '/5k-races': typeof R5kRacesRouteWithChildren
  '/_adminShell': typeof AdminShellRouteWithChildren
  '/about': typeof AboutRoute
  '/fell-races': typeof FellRacesRoute
  '/half-marathons': typeof HalfMarathonsRouteWithChildren
  '/index.html': typeof IndexDothtmlRoute
  '/junior-parkrun-events': typeof JuniorParkrunEventsRoute
  '/list-your-event': typeof ListYourEventRoute
  '/marathons': typeof MarathonsRouteWithChildren
  '/multi-terrain-races': typeof MultiTerrainRacesRoute
  '/privacy': typeof PrivacyRoute
  '/road-races': typeof RoadRacesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/running-events-next-weekend': typeof RunningEventsNextWeekendRoute
  '/running-events-this-weekend': typeof RunningEventsThisWeekendRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trail-running-events': typeof TrailRunningEventsRoute
  '/ultra-marathons': typeof UltraMarathonsRouteWithChildren
  '/10k-races/$month': typeof R10kRacesMonthRoute
  '/5k-races/$month': typeof R5kRacesMonthRoute
  '/admin/login': typeof AdminLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/half-marathons/$month': typeof HalfMarathonsMonthRoute
  '/marathons/$month': typeof MarathonsMonthRoute
  '/parkrun-events/$slug': typeof ParkrunEventsSlugRoute
  '/running-clubs/$slug': typeof RunningClubsSlugRouteWithChildren
  '/running-events/$slug': typeof RunningEventsSlugRoute
  '/ultra-marathons/$month': typeof UltraMarathonsMonthRoute
  '/admin/': typeof AdminIndexRoute
  '/parkrun-events/': typeof ParkrunEventsIndexRoute
  '/running-clubs/': typeof RunningClubsIndexRoute
  '/_adminShell/admin/claims': typeof AdminShellAdminClaimsRoute
  '/_adminShell/admin/club-claims': typeof AdminShellAdminClubClaimsRoute
  '/_adminShell/admin/search': typeof AdminShellAdminSearchRoute
  '/_adminShell/admin/sync-runs': typeof AdminShellAdminSyncRunsRoute
  '/api/public/import-clubs': typeof ApiPublicImportClubsRoute
  '/api/public/import-events': typeof ApiPublicImportEventsRoute
  '/api/public/track-search': typeof ApiPublicTrackSearchRoute
  '/api/public/track-search-click': typeof ApiPublicTrackSearchClickRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/parkrun-events/region/$region': typeof ParkrunEventsRegionRegionRoute
  '/running-clubs/$slug/claim': typeof RunningClubsSlugClaimRoute
  '/running-events/$slug_/$distance': typeof RunningEventsSlugDistanceRoute
  '/_adminShell/admin/clubs/$id': typeof AdminShellAdminClubsIdRoute
  '/_adminShell/admin/clubs/new': typeof AdminShellAdminClubsNewRoute
  '/_adminShell/admin/events/$id': typeof AdminShellAdminEventsIdRoute
  '/_adminShell/admin/events/duplicates': typeof AdminShellAdminEventsDuplicatesRoute
  '/_adminShell/admin/events/enrich-dates': typeof AdminShellAdminEventsEnrichDatesRoute
  '/api/public/admin/fix-event-urls': typeof ApiPublicAdminFixEventUrlsRoute
  '/api/public/admin/sync-england-athletics': typeof ApiPublicAdminSyncEnglandAthleticsRoute
  '/api/public/admin/sync-scottish-athletics': typeof ApiPublicAdminSyncScottishAthleticsRoute
  '/api/public/admin/sync-scottish-athletics-clubs': typeof ApiPublicAdminSyncScottishAthleticsClubsRoute
  '/api/public/hooks/send-race-reminders': typeof ApiPublicHooksSendRaceRemindersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_adminShell/admin/clubs/': typeof AdminShellAdminClubsIndexRoute
  '/_adminShell/admin/events/': typeof AdminShellAdminEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/10k-races'
    | '/5k-races'
    | '/about'
    | '/fell-races'
    | '/half-marathons'
    | '/index.html'
    | '/junior-parkrun-events'
    | '/list-your-event'
    | '/marathons'
    | '/multi-terrain-races'
    | '/privacy'
    | '/road-races'
    | '/robots.txt'
    | '/running-events-next-weekend'
    | '/running-events-this-weekend'
    | '/search'
    | '/sitemap.xml'
    | '/trail-running-events'
    | '/ultra-marathons'
    | '/10k-races/$month'
    | '/5k-races/$month'
    | '/admin/login'
    | '/email/unsubscribe'
    | '/events/$slug'
    | '/half-marathons/$month'
    | '/marathons/$month'
    | '/parkrun-events/$slug'
    | '/running-clubs/$slug'
    | '/running-events/$slug'
    | '/ultra-marathons/$month'
    | '/admin/'
    | '/parkrun-events/'
    | '/running-clubs/'
    | '/admin/claims'
    | '/admin/club-claims'
    | '/admin/search'
    | '/admin/sync-runs'
    | '/api/public/import-clubs'
    | '/api/public/import-events'
    | '/api/public/track-search'
    | '/api/public/track-search-click'
    | '/lovable/email/suppression'
    | '/parkrun-events/region/$region'
    | '/running-clubs/$slug/claim'
    | '/running-events/$slug/$distance'
    | '/admin/clubs/$id'
    | '/admin/clubs/new'
    | '/admin/events/$id'
    | '/admin/events/duplicates'
    | '/admin/events/enrich-dates'
    | '/api/public/admin/fix-event-urls'
    | '/api/public/admin/sync-england-athletics'
    | '/api/public/admin/sync-scottish-athletics'
    | '/api/public/admin/sync-scottish-athletics-clubs'
    | '/api/public/hooks/send-race-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/clubs/'
    | '/admin/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/10k-races'
    | '/5k-races'
    | '/about'
    | '/fell-races'
    | '/half-marathons'
    | '/index.html'
    | '/junior-parkrun-events'
    | '/list-your-event'
    | '/marathons'
    | '/multi-terrain-races'
    | '/privacy'
    | '/road-races'
    | '/robots.txt'
    | '/running-events-next-weekend'
    | '/running-events-this-weekend'
    | '/search'
    | '/sitemap.xml'
    | '/trail-running-events'
    | '/ultra-marathons'
    | '/10k-races/$month'
    | '/5k-races/$month'
    | '/admin/login'
    | '/email/unsubscribe'
    | '/events/$slug'
    | '/half-marathons/$month'
    | '/marathons/$month'
    | '/parkrun-events/$slug'
    | '/running-clubs/$slug'
    | '/running-events/$slug'
    | '/ultra-marathons/$month'
    | '/admin'
    | '/parkrun-events'
    | '/running-clubs'
    | '/admin/claims'
    | '/admin/club-claims'
    | '/admin/search'
    | '/admin/sync-runs'
    | '/api/public/import-clubs'
    | '/api/public/import-events'
    | '/api/public/track-search'
    | '/api/public/track-search-click'
    | '/lovable/email/suppression'
    | '/parkrun-events/region/$region'
    | '/running-clubs/$slug/claim'
    | '/running-events/$slug/$distance'
    | '/admin/clubs/$id'
    | '/admin/clubs/new'
    | '/admin/events/$id'
    | '/admin/events/duplicates'
    | '/admin/events/enrich-dates'
    | '/api/public/admin/fix-event-urls'
    | '/api/public/admin/sync-england-athletics'
    | '/api/public/admin/sync-scottish-athletics'
    | '/api/public/admin/sync-scottish-athletics-clubs'
    | '/api/public/hooks/send-race-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/clubs'
    | '/admin/events'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/10k-races'
    | '/5k-races'
    | '/_adminShell'
    | '/about'
    | '/fell-races'
    | '/half-marathons'
    | '/index.html'
    | '/junior-parkrun-events'
    | '/list-your-event'
    | '/marathons'
    | '/multi-terrain-races'
    | '/privacy'
    | '/road-races'
    | '/robots.txt'
    | '/running-events-next-weekend'
    | '/running-events-this-weekend'
    | '/search'
    | '/sitemap.xml'
    | '/trail-running-events'
    | '/ultra-marathons'
    | '/10k-races/$month'
    | '/5k-races/$month'
    | '/admin/login'
    | '/email/unsubscribe'
    | '/events/$slug'
    | '/half-marathons/$month'
    | '/marathons/$month'
    | '/parkrun-events/$slug'
    | '/running-clubs/$slug'
    | '/running-events/$slug'
    | '/ultra-marathons/$month'
    | '/admin/'
    | '/parkrun-events/'
    | '/running-clubs/'
    | '/_adminShell/admin/claims'
    | '/_adminShell/admin/club-claims'
    | '/_adminShell/admin/search'
    | '/_adminShell/admin/sync-runs'
    | '/api/public/import-clubs'
    | '/api/public/import-events'
    | '/api/public/track-search'
    | '/api/public/track-search-click'
    | '/lovable/email/suppression'
    | '/parkrun-events/region/$region'
    | '/running-clubs/$slug/claim'
    | '/running-events/$slug_/$distance'
    | '/_adminShell/admin/clubs/$id'
    | '/_adminShell/admin/clubs/new'
    | '/_adminShell/admin/events/$id'
    | '/_adminShell/admin/events/duplicates'
    | '/_adminShell/admin/events/enrich-dates'
    | '/api/public/admin/fix-event-urls'
    | '/api/public/admin/sync-england-athletics'
    | '/api/public/admin/sync-scottish-athletics'
    | '/api/public/admin/sync-scottish-athletics-clubs'
    | '/api/public/hooks/send-race-reminders'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_adminShell/admin/clubs/'
    | '/_adminShell/admin/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  R10kRacesRoute: typeof R10kRacesRouteWithChildren
  R5kRacesRoute: typeof R5kRacesRouteWithChildren
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AboutRoute: typeof AboutRoute
  FellRacesRoute: typeof FellRacesRoute
  HalfMarathonsRoute: typeof HalfMarathonsRouteWithChildren
  IndexDothtmlRoute: typeof IndexDothtmlRoute
  JuniorParkrunEventsRoute: typeof JuniorParkrunEventsRoute
  ListYourEventRoute: typeof ListYourEventRoute
  MarathonsRoute: typeof MarathonsRouteWithChildren
  MultiTerrainRacesRoute: typeof MultiTerrainRacesRoute
  PrivacyRoute: typeof PrivacyRoute
  RoadRacesRoute: typeof RoadRacesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  RunningEventsNextWeekendRoute: typeof RunningEventsNextWeekendRoute
  RunningEventsThisWeekendRoute: typeof RunningEventsThisWeekendRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrailRunningEventsRoute: typeof TrailRunningEventsRoute
  UltraMarathonsRoute: typeof UltraMarathonsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EventsSlugRoute: typeof EventsSlugRoute
  ParkrunEventsSlugRoute: typeof ParkrunEventsSlugRoute
  RunningClubsSlugRoute: typeof RunningClubsSlugRouteWithChildren
  RunningEventsSlugRoute: typeof RunningEventsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ParkrunEventsIndexRoute: typeof ParkrunEventsIndexRoute
  RunningClubsIndexRoute: typeof RunningClubsIndexRoute
  ApiPublicImportClubsRoute: typeof ApiPublicImportClubsRoute
  ApiPublicImportEventsRoute: typeof ApiPublicImportEventsRoute
  ApiPublicTrackSearchRoute: typeof ApiPublicTrackSearchRoute
  ApiPublicTrackSearchClickRoute: typeof ApiPublicTrackSearchClickRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ParkrunEventsRegionRegionRoute: typeof ParkrunEventsRegionRegionRoute
  RunningEventsSlugDistanceRoute: typeof RunningEventsSlugDistanceRoute
  ApiPublicAdminFixEventUrlsRoute: typeof ApiPublicAdminFixEventUrlsRoute
  ApiPublicAdminSyncEnglandAthleticsRoute: typeof ApiPublicAdminSyncEnglandAthleticsRoute
  ApiPublicAdminSyncScottishAthleticsRoute: typeof ApiPublicAdminSyncScottishAthleticsRoute
  ApiPublicAdminSyncScottishAthleticsClubsRoute: typeof ApiPublicAdminSyncScottishAthleticsClubsRoute
  ApiPublicHooksSendRaceRemindersRoute: typeof ApiPublicHooksSendRaceRemindersRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ultra-marathons': {
      id: '/ultra-marathons'
      path: '/ultra-marathons'
      fullPath: '/ultra-marathons'
      preLoaderRoute: typeof UltraMarathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trail-running-events': {
      id: '/trail-running-events'
      path: '/trail-running-events'
      fullPath: '/trail-running-events'
      preLoaderRoute: typeof TrailRunningEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running-events-this-weekend': {
      id: '/running-events-this-weekend'
      path: '/running-events-this-weekend'
      fullPath: '/running-events-this-weekend'
      preLoaderRoute: typeof RunningEventsThisWeekendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running-events-next-weekend': {
      id: '/running-events-next-weekend'
      path: '/running-events-next-weekend'
      fullPath: '/running-events-next-weekend'
      preLoaderRoute: typeof RunningEventsNextWeekendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/road-races': {
      id: '/road-races'
      path: '/road-races'
      fullPath: '/road-races'
      preLoaderRoute: typeof RoadRacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-terrain-races': {
      id: '/multi-terrain-races'
      path: '/multi-terrain-races'
      fullPath: '/multi-terrain-races'
      preLoaderRoute: typeof MultiTerrainRacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marathons': {
      id: '/marathons'
      path: '/marathons'
      fullPath: '/marathons'
      preLoaderRoute: typeof MarathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-event': {
      id: '/list-your-event'
      path: '/list-your-event'
      fullPath: '/list-your-event'
      preLoaderRoute: typeof ListYourEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junior-parkrun-events': {
      id: '/junior-parkrun-events'
      path: '/junior-parkrun-events'
      fullPath: '/junior-parkrun-events'
      preLoaderRoute: typeof JuniorParkrunEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.html': {
      id: '/index.html'
      path: '/index.html'
      fullPath: '/index.html'
      preLoaderRoute: typeof IndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/half-marathons': {
      id: '/half-marathons'
      path: '/half-marathons'
      fullPath: '/half-marathons'
      preLoaderRoute: typeof HalfMarathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fell-races': {
      id: '/fell-races'
      path: '/fell-races'
      fullPath: '/fell-races'
      preLoaderRoute: typeof FellRacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminShell': {
      id: '/_adminShell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5k-races': {
      id: '/5k-races'
      path: '/5k-races'
      fullPath: '/5k-races'
      preLoaderRoute: typeof R5kRacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/10k-races': {
      id: '/10k-races'
      path: '/10k-races'
      fullPath: '/10k-races'
      preLoaderRoute: typeof R10kRacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running-clubs/': {
      id: '/running-clubs/'
      path: '/running-clubs'
      fullPath: '/running-clubs/'
      preLoaderRoute: typeof RunningClubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkrun-events/': {
      id: '/parkrun-events/'
      path: '/parkrun-events'
      fullPath: '/parkrun-events/'
      preLoaderRoute: typeof ParkrunEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ultra-marathons/$month': {
      id: '/ultra-marathons/$month'
      path: '/$month'
      fullPath: '/ultra-marathons/$month'
      preLoaderRoute: typeof UltraMarathonsMonthRouteImport
      parentRoute: typeof UltraMarathonsRoute
    }
    '/running-events/$slug': {
      id: '/running-events/$slug'
      path: '/running-events/$slug'
      fullPath: '/running-events/$slug'
      preLoaderRoute: typeof RunningEventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running-clubs/$slug': {
      id: '/running-clubs/$slug'
      path: '/running-clubs/$slug'
      fullPath: '/running-clubs/$slug'
      preLoaderRoute: typeof RunningClubsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkrun-events/$slug': {
      id: '/parkrun-events/$slug'
      path: '/parkrun-events/$slug'
      fullPath: '/parkrun-events/$slug'
      preLoaderRoute: typeof ParkrunEventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marathons/$month': {
      id: '/marathons/$month'
      path: '/$month'
      fullPath: '/marathons/$month'
      preLoaderRoute: typeof MarathonsMonthRouteImport
      parentRoute: typeof MarathonsRoute
    }
    '/half-marathons/$month': {
      id: '/half-marathons/$month'
      path: '/$month'
      fullPath: '/half-marathons/$month'
      preLoaderRoute: typeof HalfMarathonsMonthRouteImport
      parentRoute: typeof HalfMarathonsRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5k-races/$month': {
      id: '/5k-races/$month'
      path: '/$month'
      fullPath: '/5k-races/$month'
      preLoaderRoute: typeof R5kRacesMonthRouteImport
      parentRoute: typeof R5kRacesRoute
    }
    '/10k-races/$month': {
      id: '/10k-races/$month'
      path: '/$month'
      fullPath: '/10k-races/$month'
      preLoaderRoute: typeof R10kRacesMonthRouteImport
      parentRoute: typeof R10kRacesRoute
    }
    '/running-events/$slug_/$distance': {
      id: '/running-events/$slug_/$distance'
      path: '/running-events/$slug/$distance'
      fullPath: '/running-events/$slug/$distance'
      preLoaderRoute: typeof RunningEventsSlugDistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running-clubs/$slug/claim': {
      id: '/running-clubs/$slug/claim'
      path: '/claim'
      fullPath: '/running-clubs/$slug/claim'
      preLoaderRoute: typeof RunningClubsSlugClaimRouteImport
      parentRoute: typeof RunningClubsSlugRoute
    }
    '/parkrun-events/region/$region': {
      id: '/parkrun-events/region/$region'
      path: '/parkrun-events/region/$region'
      fullPath: '/parkrun-events/region/$region'
      preLoaderRoute: typeof ParkrunEventsRegionRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-search-click': {
      id: '/api/public/track-search-click'
      path: '/api/public/track-search-click'
      fullPath: '/api/public/track-search-click'
      preLoaderRoute: typeof ApiPublicTrackSearchClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track-search': {
      id: '/api/public/track-search'
      path: '/api/public/track-search'
      fullPath: '/api/public/track-search'
      preLoaderRoute: typeof ApiPublicTrackSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-events': {
      id: '/api/public/import-events'
      path: '/api/public/import-events'
      fullPath: '/api/public/import-events'
      preLoaderRoute: typeof ApiPublicImportEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-clubs': {
      id: '/api/public/import-clubs'
      path: '/api/public/import-clubs'
      fullPath: '/api/public/import-clubs'
      preLoaderRoute: typeof ApiPublicImportClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminShell/admin/sync-runs': {
      id: '/_adminShell/admin/sync-runs'
      path: '/admin/sync-runs'
      fullPath: '/admin/sync-runs'
      preLoaderRoute: typeof AdminShellAdminSyncRunsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_adminShell/admin/search': {
      id: '/_adminShell/admin/search'
      path: '/admin/search'
      fullPath: '/admin/search'
      preLoaderRoute: typeof AdminShellAdminSearchRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_adminShell/admin/club-claims': {
      id: '/_adminShell/admin/club-claims'
      path: '/admin/club-claims'
      fullPath: '/admin/club-claims'
      preLoaderRoute: typeof AdminShellAdminClubClaimsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_adminShell/admin/claims': {
      id: '/_adminShell/admin/claims'
      path: '/admin/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminShellAdminClaimsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_adminShell/admin/events/': {
      id: '/_adminShell/admin/events/'
      path: '/admin/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminShellAdminEventsIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_adminShell/admin/clubs/': {
      id: '/_adminShell/admin/clubs/'
      path: '/admin/clubs'
      fullPath: '/admin/clubs/'
      preLoaderRoute: typeof AdminShellAdminClubsIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-race-reminders': {
      id: '/api/public/hooks/send-race-reminders'
      path: '/api/public/hooks/send-race-reminders'
      fullPath: '/api/public/hooks/send-race-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRaceRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/sync-scottish-athletics-clubs': {
      id: '/api/public/admin/sync-scottish-athletics-clubs'
      path: '/api/public/admin/sync-scottish-athletics-clubs'
      fullPath: '/api/public/admin/sync-scottish-athletics-clubs'
      preLoaderRoute: typeof ApiPublicAdminSyncScottishAthleticsClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/sync-scottish-athletics': {
      id: '/api/public/admin/sync-scottish-athletics'
      path: '/api/public/admin/sync-scottish-athletics'
      fullPath: '/api/public/admin/sync-scottish-athletics'
      preLoaderRoute: typeof ApiPublicAdminSyncScottishAthleticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/sync-england-athletics': {
      id: '/api/public/admin/sync-england-athletics'
      path: '/api/public/admin/sync-england-athletics'
      fullPath: '/api/public/admin/sync-england-athletics'
      preLoaderRoute: typeof ApiPublicAdminSyncEnglandAthleticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/fix-event-urls': {
      id: '/api/public/admin/fix-event-urls'
      path: '/api/public/admin/fix-event-urls'
      fullPath: '/api/public/admin/fix-event-urls'
      preLoaderRoute: typeof ApiPublicAdminFixEventUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminShell/admin/events/enrich-dates': {
      id: '/_adminShell/admin/events/enrich-dates'
      path: '/admin/events/enrich-dates'
      fullPath: '/admin/events/enrich-dates'
      preLoaderRoute: typeof AdminShellAdminEventsEnrichDatesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_adminShell/admin/events/duplicates': {
      id: '/_adminShell/admin/events/duplicates'
      path: '/admin/events/duplicates'
      fullPath: '/admin/events/duplicates'
      preLoaderRoute: typeof AdminShellAdminEventsDuplicatesRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_adminShell/admin/events/$id': {
      id: '/_adminShell/admin/events/$id'
      path: '/admin/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminShellAdminEventsIdRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_adminShell/admin/clubs/new': {
      id: '/_adminShell/admin/clubs/new'
      path: '/admin/clubs/new'
      fullPath: '/admin/clubs/new'
      preLoaderRoute: typeof AdminShellAdminClubsNewRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_adminShell/admin/clubs/$id': {
      id: '/_adminShell/admin/clubs/$id'
      path: '/admin/clubs/$id'
      fullPath: '/admin/clubs/$id'
      preLoaderRoute: typeof AdminShellAdminClubsIdRouteImport
      parentRoute: typeof AdminShellRoute
    }
  }
}

interface R10kRacesRouteChildren {
  R10kRacesMonthRoute: typeof R10kRacesMonthRoute
}

const R10kRacesRouteChildren: R10kRacesRouteChildren = {
  R10kRacesMonthRoute: R10kRacesMonthRoute,
}

const R10kRacesRouteWithChildren = R10kRacesRoute._addFileChildren(
  R10kRacesRouteChildren,
)

interface R5kRacesRouteChildren {
  R5kRacesMonthRoute: typeof R5kRacesMonthRoute
}

const R5kRacesRouteChildren: R5kRacesRouteChildren = {
  R5kRacesMonthRoute: R5kRacesMonthRoute,
}

const R5kRacesRouteWithChildren = R5kRacesRoute._addFileChildren(
  R5kRacesRouteChildren,
)

interface AdminShellRouteChildren {
  AdminShellAdminClaimsRoute: typeof AdminShellAdminClaimsRoute
  AdminShellAdminClubClaimsRoute: typeof AdminShellAdminClubClaimsRoute
  AdminShellAdminSearchRoute: typeof AdminShellAdminSearchRoute
  AdminShellAdminSyncRunsRoute: typeof AdminShellAdminSyncRunsRoute
  AdminShellAdminClubsIdRoute: typeof AdminShellAdminClubsIdRoute
  AdminShellAdminClubsNewRoute: typeof AdminShellAdminClubsNewRoute
  AdminShellAdminEventsIdRoute: typeof AdminShellAdminEventsIdRoute
  AdminShellAdminEventsDuplicatesRoute: typeof AdminShellAdminEventsDuplicatesRoute
  AdminShellAdminEventsEnrichDatesRoute: typeof AdminShellAdminEventsEnrichDatesRoute
  AdminShellAdminClubsIndexRoute: typeof AdminShellAdminClubsIndexRoute
  AdminShellAdminEventsIndexRoute: typeof AdminShellAdminEventsIndexRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellAdminClaimsRoute: AdminShellAdminClaimsRoute,
  AdminShellAdminClubClaimsRoute: AdminShellAdminClubClaimsRoute,
  AdminShellAdminSearchRoute: AdminShellAdminSearchRoute,
  AdminShellAdminSyncRunsRoute: AdminShellAdminSyncRunsRoute,
  AdminShellAdminClubsIdRoute: AdminShellAdminClubsIdRoute,
  AdminShellAdminClubsNewRoute: AdminShellAdminClubsNewRoute,
  AdminShellAdminEventsIdRoute: AdminShellAdminEventsIdRoute,
  AdminShellAdminEventsDuplicatesRoute: AdminShellAdminEventsDuplicatesRoute,
  AdminShellAdminEventsEnrichDatesRoute: AdminShellAdminEventsEnrichDatesRoute,
  AdminShellAdminClubsIndexRoute: AdminShellAdminClubsIndexRoute,
  AdminShellAdminEventsIndexRoute: AdminShellAdminEventsIndexRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

interface HalfMarathonsRouteChildren {
  HalfMarathonsMonthRoute: typeof HalfMarathonsMonthRoute
}

const HalfMarathonsRouteChildren: HalfMarathonsRouteChildren = {
  HalfMarathonsMonthRoute: HalfMarathonsMonthRoute,
}

const HalfMarathonsRouteWithChildren = HalfMarathonsRoute._addFileChildren(
  HalfMarathonsRouteChildren,
)

interface MarathonsRouteChildren {
  MarathonsMonthRoute: typeof MarathonsMonthRoute
}

const MarathonsRouteChildren: MarathonsRouteChildren = {
  MarathonsMonthRoute: MarathonsMonthRoute,
}

const MarathonsRouteWithChildren = MarathonsRoute._addFileChildren(
  MarathonsRouteChildren,
)

interface UltraMarathonsRouteChildren {
  UltraMarathonsMonthRoute: typeof UltraMarathonsMonthRoute
}

const UltraMarathonsRouteChildren: UltraMarathonsRouteChildren = {
  UltraMarathonsMonthRoute: UltraMarathonsMonthRoute,
}

const UltraMarathonsRouteWithChildren = UltraMarathonsRoute._addFileChildren(
  UltraMarathonsRouteChildren,
)

interface RunningClubsSlugRouteChildren {
  RunningClubsSlugClaimRoute: typeof RunningClubsSlugClaimRoute
}

const RunningClubsSlugRouteChildren: RunningClubsSlugRouteChildren = {
  RunningClubsSlugClaimRoute: RunningClubsSlugClaimRoute,
}

const RunningClubsSlugRouteWithChildren =
  RunningClubsSlugRoute._addFileChildren(RunningClubsSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  R10kRacesRoute: R10kRacesRouteWithChildren,
  R5kRacesRoute: R5kRacesRouteWithChildren,
  AdminShellRoute: AdminShellRouteWithChildren,
  AboutRoute: AboutRoute,
  FellRacesRoute: FellRacesRoute,
  HalfMarathonsRoute: HalfMarathonsRouteWithChildren,
  IndexDothtmlRoute: IndexDothtmlRoute,
  JuniorParkrunEventsRoute: JuniorParkrunEventsRoute,
  ListYourEventRoute: ListYourEventRoute,
  MarathonsRoute: MarathonsRouteWithChildren,
  MultiTerrainRacesRoute: MultiTerrainRacesRoute,
  PrivacyRoute: PrivacyRoute,
  RoadRacesRoute: RoadRacesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  RunningEventsNextWeekendRoute: RunningEventsNextWeekendRoute,
  RunningEventsThisWeekendRoute: RunningEventsThisWeekendRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrailRunningEventsRoute: TrailRunningEventsRoute,
  UltraMarathonsRoute: UltraMarathonsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EventsSlugRoute: EventsSlugRoute,
  ParkrunEventsSlugRoute: ParkrunEventsSlugRoute,
  RunningClubsSlugRoute: RunningClubsSlugRouteWithChildren,
  RunningEventsSlugRoute: RunningEventsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ParkrunEventsIndexRoute: ParkrunEventsIndexRoute,
  RunningClubsIndexRoute: RunningClubsIndexRoute,
  ApiPublicImportClubsRoute: ApiPublicImportClubsRoute,
  ApiPublicImportEventsRoute: ApiPublicImportEventsRoute,
  ApiPublicTrackSearchRoute: ApiPublicTrackSearchRoute,
  ApiPublicTrackSearchClickRoute: ApiPublicTrackSearchClickRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ParkrunEventsRegionRegionRoute: ParkrunEventsRegionRegionRoute,
  RunningEventsSlugDistanceRoute: RunningEventsSlugDistanceRoute,
  ApiPublicAdminFixEventUrlsRoute: ApiPublicAdminFixEventUrlsRoute,
  ApiPublicAdminSyncEnglandAthleticsRoute:
    ApiPublicAdminSyncEnglandAthleticsRoute,
  ApiPublicAdminSyncScottishAthleticsRoute:
    ApiPublicAdminSyncScottishAthleticsRoute,
  ApiPublicAdminSyncScottishAthleticsClubsRoute:
    ApiPublicAdminSyncScottishAthleticsClubsRoute,
  ApiPublicHooksSendRaceRemindersRoute: ApiPublicHooksSendRaceRemindersRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
