/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UltraMarathonsRouteImport } from './routes/ultra-marathons'
import { Route as TrailRunningEventsRouteImport } from './routes/trail-running-events'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MarathonsRouteImport } from './routes/marathons'
import { Route as ListYourEventRouteImport } from './routes/list-your-event'
import { Route as JuniorParkrunEventsRouteImport } from './routes/junior-parkrun-events'
import { Route as IndexDothtmlRouteImport } from './routes/index[.]html'
import { Route as HalfMarathonsRouteImport } from './routes/half-marathons'
import { Route as AdminShellRouteImport } from './routes/_adminShell'
import { Route as R5kRacesRouteImport } from './routes/5k-races'
import { Route as R10kRacesRouteImport } from './routes/10k-races'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ParkrunEventsIndexRouteImport } from './routes/parkrun-events.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RunningEventsSlugRouteImport } from './routes/running-events.$slug'
import { Route as ParkrunEventsSlugRouteImport } from './routes/parkrun-events.$slug'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as RunningEventsSlugDistanceRouteImport } from './routes/running-events.$slug_.$distance'
import { Route as ParkrunEventsRegionRegionRouteImport } from './routes/parkrun-events.region.$region'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicImportEventsRouteImport } from './routes/api/public/import-events'
import { Route as AdminShellAdminClaimsRouteImport } from './routes/_adminShell.admin.claims'
import { Route as AdminShellAdminEventsIndexRouteImport } from './routes/_adminShell.admin.events.index'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicAdminSyncScottishAthleticsRouteImport } from './routes/api/public/admin/sync-scottish-athletics'
import { Route as ApiPublicAdminSyncEnglandAthleticsRouteImport } from './routes/api/public/admin/sync-england-athletics'
import { Route as ApiPublicAdminFixEventUrlsRouteImport } from './routes/api/public/admin/fix-event-urls'
import { Route as AdminShellAdminEventsIdRouteImport } from './routes/_adminShell.admin.events.$id'

const UltraMarathonsRoute = UltraMarathonsRouteImport.update({
  id: '/ultra-marathons',
  path: '/ultra-marathons',
  getParentRoute: () => rootRouteImport,
} as any)
const TrailRunningEventsRoute = TrailRunningEventsRouteImport.update({
  id: '/trail-running-events',
  path: '/trail-running-events',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarathonsRoute = MarathonsRouteImport.update({
  id: '/marathons',
  path: '/marathons',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourEventRoute = ListYourEventRouteImport.update({
  id: '/list-your-event',
  path: '/list-your-event',
  getParentRoute: () => rootRouteImport,
} as any)
const JuniorParkrunEventsRoute = JuniorParkrunEventsRouteImport.update({
  id: '/junior-parkrun-events',
  path: '/junior-parkrun-events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexDothtmlRoute = IndexDothtmlRouteImport.update({
  id: '/index.html',
  path: '/index.html',
  getParentRoute: () => rootRouteImport,
} as any)
const HalfMarathonsRoute = HalfMarathonsRouteImport.update({
  id: '/half-marathons',
  path: '/half-marathons',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/_adminShell',
  getParentRoute: () => rootRouteImport,
} as any)
const R5kRacesRoute = R5kRacesRouteImport.update({
  id: '/5k-races',
  path: '/5k-races',
  getParentRoute: () => rootRouteImport,
} as any)
const R10kRacesRoute = R10kRacesRouteImport.update({
  id: '/10k-races',
  path: '/10k-races',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkrunEventsIndexRoute = ParkrunEventsIndexRouteImport.update({
  id: '/parkrun-events/',
  path: '/parkrun-events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningEventsSlugRoute = RunningEventsSlugRouteImport.update({
  id: '/running-events/$slug',
  path: '/running-events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkrunEventsSlugRoute = ParkrunEventsSlugRouteImport.update({
  id: '/parkrun-events/$slug',
  path: '/parkrun-events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/events/$slug',
  path: '/events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningEventsSlugDistanceRoute =
  RunningEventsSlugDistanceRouteImport.update({
    id: '/running-events/$slug_/$distance',
    path: '/running-events/$slug/$distance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ParkrunEventsRegionRegionRoute =
  ParkrunEventsRegionRegionRouteImport.update({
    id: '/parkrun-events/region/$region',
    path: '/parkrun-events/region/$region',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImportEventsRoute = ApiPublicImportEventsRouteImport.update({
  id: '/api/public/import-events',
  path: '/api/public/import-events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellAdminClaimsRoute = AdminShellAdminClaimsRouteImport.update({
  id: '/admin/claims',
  path: '/admin/claims',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAdminEventsIndexRoute =
  AdminShellAdminEventsIndexRouteImport.update({
    id: '/admin/events/',
    path: '/admin/events/',
    getParentRoute: () => AdminShellRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSyncScottishAthleticsRoute =
  ApiPublicAdminSyncScottishAthleticsRouteImport.update({
    id: '/api/public/admin/sync-scottish-athletics',
    path: '/api/public/admin/sync-scottish-athletics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminSyncEnglandAthleticsRoute =
  ApiPublicAdminSyncEnglandAthleticsRouteImport.update({
    id: '/api/public/admin/sync-england-athletics',
    path: '/api/public/admin/sync-england-athletics',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminFixEventUrlsRoute =
  ApiPublicAdminFixEventUrlsRouteImport.update({
    id: '/api/public/admin/fix-event-urls',
    path: '/api/public/admin/fix-event-urls',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminShellAdminEventsIdRoute = AdminShellAdminEventsIdRouteImport.update({
  id: '/admin/events/$id',
  path: '/admin/events/$id',
  getParentRoute: () => AdminShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/10k-races': typeof R10kRacesRoute
  '/5k-races': typeof R5kRacesRoute
  '/half-marathons': typeof HalfMarathonsRoute
  '/index.html': typeof IndexDothtmlRoute
  '/junior-parkrun-events': typeof JuniorParkrunEventsRoute
  '/list-your-event': typeof ListYourEventRoute
  '/marathons': typeof MarathonsRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trail-running-events': typeof TrailRunningEventsRoute
  '/ultra-marathons': typeof UltraMarathonsRoute
  '/admin/login': typeof AdminLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/parkrun-events/$slug': typeof ParkrunEventsSlugRoute
  '/running-events/$slug': typeof RunningEventsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/parkrun-events/': typeof ParkrunEventsIndexRoute
  '/admin/claims': typeof AdminShellAdminClaimsRoute
  '/api/public/import-events': typeof ApiPublicImportEventsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/parkrun-events/region/$region': typeof ParkrunEventsRegionRegionRoute
  '/running-events/$slug/$distance': typeof RunningEventsSlugDistanceRoute
  '/admin/events/$id': typeof AdminShellAdminEventsIdRoute
  '/api/public/admin/fix-event-urls': typeof ApiPublicAdminFixEventUrlsRoute
  '/api/public/admin/sync-england-athletics': typeof ApiPublicAdminSyncEnglandAthleticsRoute
  '/api/public/admin/sync-scottish-athletics': typeof ApiPublicAdminSyncScottishAthleticsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/events/': typeof AdminShellAdminEventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/10k-races': typeof R10kRacesRoute
  '/5k-races': typeof R5kRacesRoute
  '/half-marathons': typeof HalfMarathonsRoute
  '/index.html': typeof IndexDothtmlRoute
  '/junior-parkrun-events': typeof JuniorParkrunEventsRoute
  '/list-your-event': typeof ListYourEventRoute
  '/marathons': typeof MarathonsRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trail-running-events': typeof TrailRunningEventsRoute
  '/ultra-marathons': typeof UltraMarathonsRoute
  '/admin/login': typeof AdminLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/parkrun-events/$slug': typeof ParkrunEventsSlugRoute
  '/running-events/$slug': typeof RunningEventsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/parkrun-events': typeof ParkrunEventsIndexRoute
  '/admin/claims': typeof AdminShellAdminClaimsRoute
  '/api/public/import-events': typeof ApiPublicImportEventsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/parkrun-events/region/$region': typeof ParkrunEventsRegionRegionRoute
  '/running-events/$slug/$distance': typeof RunningEventsSlugDistanceRoute
  '/admin/events/$id': typeof AdminShellAdminEventsIdRoute
  '/api/public/admin/fix-event-urls': typeof ApiPublicAdminFixEventUrlsRoute
  '/api/public/admin/sync-england-athletics': typeof ApiPublicAdminSyncEnglandAthleticsRoute
  '/api/public/admin/sync-scottish-athletics': typeof ApiPublicAdminSyncScottishAthleticsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/admin/events': typeof AdminShellAdminEventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/10k-races': typeof R10kRacesRoute
  '/5k-races': typeof R5kRacesRoute
  '/_adminShell': typeof AdminShellRouteWithChildren
  '/half-marathons': typeof HalfMarathonsRoute
  '/index.html': typeof IndexDothtmlRoute
  '/junior-parkrun-events': typeof JuniorParkrunEventsRoute
  '/list-your-event': typeof ListYourEventRoute
  '/marathons': typeof MarathonsRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trail-running-events': typeof TrailRunningEventsRoute
  '/ultra-marathons': typeof UltraMarathonsRoute
  '/admin/login': typeof AdminLoginRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/events/$slug': typeof EventsSlugRoute
  '/parkrun-events/$slug': typeof ParkrunEventsSlugRoute
  '/running-events/$slug': typeof RunningEventsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/parkrun-events/': typeof ParkrunEventsIndexRoute
  '/_adminShell/admin/claims': typeof AdminShellAdminClaimsRoute
  '/api/public/import-events': typeof ApiPublicImportEventsRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/parkrun-events/region/$region': typeof ParkrunEventsRegionRegionRoute
  '/running-events/$slug_/$distance': typeof RunningEventsSlugDistanceRoute
  '/_adminShell/admin/events/$id': typeof AdminShellAdminEventsIdRoute
  '/api/public/admin/fix-event-urls': typeof ApiPublicAdminFixEventUrlsRoute
  '/api/public/admin/sync-england-athletics': typeof ApiPublicAdminSyncEnglandAthleticsRoute
  '/api/public/admin/sync-scottish-athletics': typeof ApiPublicAdminSyncScottishAthleticsRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
  '/_adminShell/admin/events/': typeof AdminShellAdminEventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/10k-races'
    | '/5k-races'
    | '/half-marathons'
    | '/index.html'
    | '/junior-parkrun-events'
    | '/list-your-event'
    | '/marathons'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/trail-running-events'
    | '/ultra-marathons'
    | '/admin/login'
    | '/email/unsubscribe'
    | '/events/$slug'
    | '/parkrun-events/$slug'
    | '/running-events/$slug'
    | '/admin/'
    | '/parkrun-events/'
    | '/admin/claims'
    | '/api/public/import-events'
    | '/lovable/email/suppression'
    | '/parkrun-events/region/$region'
    | '/running-events/$slug/$distance'
    | '/admin/events/$id'
    | '/api/public/admin/fix-event-urls'
    | '/api/public/admin/sync-england-athletics'
    | '/api/public/admin/sync-scottish-athletics'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/10k-races'
    | '/5k-races'
    | '/half-marathons'
    | '/index.html'
    | '/junior-parkrun-events'
    | '/list-your-event'
    | '/marathons'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/trail-running-events'
    | '/ultra-marathons'
    | '/admin/login'
    | '/email/unsubscribe'
    | '/events/$slug'
    | '/parkrun-events/$slug'
    | '/running-events/$slug'
    | '/admin'
    | '/parkrun-events'
    | '/admin/claims'
    | '/api/public/import-events'
    | '/lovable/email/suppression'
    | '/parkrun-events/region/$region'
    | '/running-events/$slug/$distance'
    | '/admin/events/$id'
    | '/api/public/admin/fix-event-urls'
    | '/api/public/admin/sync-england-athletics'
    | '/api/public/admin/sync-scottish-athletics'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/admin/events'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/10k-races'
    | '/5k-races'
    | '/_adminShell'
    | '/half-marathons'
    | '/index.html'
    | '/junior-parkrun-events'
    | '/list-your-event'
    | '/marathons'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/trail-running-events'
    | '/ultra-marathons'
    | '/admin/login'
    | '/email/unsubscribe'
    | '/events/$slug'
    | '/parkrun-events/$slug'
    | '/running-events/$slug'
    | '/admin/'
    | '/parkrun-events/'
    | '/_adminShell/admin/claims'
    | '/api/public/import-events'
    | '/lovable/email/suppression'
    | '/parkrun-events/region/$region'
    | '/running-events/$slug_/$distance'
    | '/_adminShell/admin/events/$id'
    | '/api/public/admin/fix-event-urls'
    | '/api/public/admin/sync-england-athletics'
    | '/api/public/admin/sync-scottish-athletics'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
    | '/_adminShell/admin/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  R10kRacesRoute: typeof R10kRacesRoute
  R5kRacesRoute: typeof R5kRacesRoute
  AdminShellRoute: typeof AdminShellRouteWithChildren
  HalfMarathonsRoute: typeof HalfMarathonsRoute
  IndexDothtmlRoute: typeof IndexDothtmlRoute
  JuniorParkrunEventsRoute: typeof JuniorParkrunEventsRoute
  ListYourEventRoute: typeof ListYourEventRoute
  MarathonsRoute: typeof MarathonsRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrailRunningEventsRoute: typeof TrailRunningEventsRoute
  UltraMarathonsRoute: typeof UltraMarathonsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EventsSlugRoute: typeof EventsSlugRoute
  ParkrunEventsSlugRoute: typeof ParkrunEventsSlugRoute
  RunningEventsSlugRoute: typeof RunningEventsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ParkrunEventsIndexRoute: typeof ParkrunEventsIndexRoute
  ApiPublicImportEventsRoute: typeof ApiPublicImportEventsRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ParkrunEventsRegionRegionRoute: typeof ParkrunEventsRegionRegionRoute
  RunningEventsSlugDistanceRoute: typeof RunningEventsSlugDistanceRoute
  ApiPublicAdminFixEventUrlsRoute: typeof ApiPublicAdminFixEventUrlsRoute
  ApiPublicAdminSyncEnglandAthleticsRoute: typeof ApiPublicAdminSyncEnglandAthleticsRoute
  ApiPublicAdminSyncScottishAthleticsRoute: typeof ApiPublicAdminSyncScottishAthleticsRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ultra-marathons': {
      id: '/ultra-marathons'
      path: '/ultra-marathons'
      fullPath: '/ultra-marathons'
      preLoaderRoute: typeof UltraMarathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trail-running-events': {
      id: '/trail-running-events'
      path: '/trail-running-events'
      fullPath: '/trail-running-events'
      preLoaderRoute: typeof TrailRunningEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marathons': {
      id: '/marathons'
      path: '/marathons'
      fullPath: '/marathons'
      preLoaderRoute: typeof MarathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-event': {
      id: '/list-your-event'
      path: '/list-your-event'
      fullPath: '/list-your-event'
      preLoaderRoute: typeof ListYourEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/junior-parkrun-events': {
      id: '/junior-parkrun-events'
      path: '/junior-parkrun-events'
      fullPath: '/junior-parkrun-events'
      preLoaderRoute: typeof JuniorParkrunEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.html': {
      id: '/index.html'
      path: '/index.html'
      fullPath: '/index.html'
      preLoaderRoute: typeof IndexDothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/half-marathons': {
      id: '/half-marathons'
      path: '/half-marathons'
      fullPath: '/half-marathons'
      preLoaderRoute: typeof HalfMarathonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminShell': {
      id: '/_adminShell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/5k-races': {
      id: '/5k-races'
      path: '/5k-races'
      fullPath: '/5k-races'
      preLoaderRoute: typeof R5kRacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/10k-races': {
      id: '/10k-races'
      path: '/10k-races'
      fullPath: '/10k-races'
      preLoaderRoute: typeof R10kRacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkrun-events/': {
      id: '/parkrun-events/'
      path: '/parkrun-events'
      fullPath: '/parkrun-events/'
      preLoaderRoute: typeof ParkrunEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running-events/$slug': {
      id: '/running-events/$slug'
      path: '/running-events/$slug'
      fullPath: '/running-events/$slug'
      preLoaderRoute: typeof RunningEventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkrun-events/$slug': {
      id: '/parkrun-events/$slug'
      path: '/parkrun-events/$slug'
      fullPath: '/parkrun-events/$slug'
      preLoaderRoute: typeof ParkrunEventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/events/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running-events/$slug_/$distance': {
      id: '/running-events/$slug_/$distance'
      path: '/running-events/$slug/$distance'
      fullPath: '/running-events/$slug/$distance'
      preLoaderRoute: typeof RunningEventsSlugDistanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkrun-events/region/$region': {
      id: '/parkrun-events/region/$region'
      path: '/parkrun-events/region/$region'
      fullPath: '/parkrun-events/region/$region'
      preLoaderRoute: typeof ParkrunEventsRegionRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-events': {
      id: '/api/public/import-events'
      path: '/api/public/import-events'
      fullPath: '/api/public/import-events'
      preLoaderRoute: typeof ApiPublicImportEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminShell/admin/claims': {
      id: '/_adminShell/admin/claims'
      path: '/admin/claims'
      fullPath: '/admin/claims'
      preLoaderRoute: typeof AdminShellAdminClaimsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/_adminShell/admin/events/': {
      id: '/_adminShell/admin/events/'
      path: '/admin/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminShellAdminEventsIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/sync-scottish-athletics': {
      id: '/api/public/admin/sync-scottish-athletics'
      path: '/api/public/admin/sync-scottish-athletics'
      fullPath: '/api/public/admin/sync-scottish-athletics'
      preLoaderRoute: typeof ApiPublicAdminSyncScottishAthleticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/sync-england-athletics': {
      id: '/api/public/admin/sync-england-athletics'
      path: '/api/public/admin/sync-england-athletics'
      fullPath: '/api/public/admin/sync-england-athletics'
      preLoaderRoute: typeof ApiPublicAdminSyncEnglandAthleticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/fix-event-urls': {
      id: '/api/public/admin/fix-event-urls'
      path: '/api/public/admin/fix-event-urls'
      fullPath: '/api/public/admin/fix-event-urls'
      preLoaderRoute: typeof ApiPublicAdminFixEventUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_adminShell/admin/events/$id': {
      id: '/_adminShell/admin/events/$id'
      path: '/admin/events/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminShellAdminEventsIdRouteImport
      parentRoute: typeof AdminShellRoute
    }
  }
}

interface AdminShellRouteChildren {
  AdminShellAdminClaimsRoute: typeof AdminShellAdminClaimsRoute
  AdminShellAdminEventsIdRoute: typeof AdminShellAdminEventsIdRoute
  AdminShellAdminEventsIndexRoute: typeof AdminShellAdminEventsIndexRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellAdminClaimsRoute: AdminShellAdminClaimsRoute,
  AdminShellAdminEventsIdRoute: AdminShellAdminEventsIdRoute,
  AdminShellAdminEventsIndexRoute: AdminShellAdminEventsIndexRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  R10kRacesRoute: R10kRacesRoute,
  R5kRacesRoute: R5kRacesRoute,
  AdminShellRoute: AdminShellRouteWithChildren,
  HalfMarathonsRoute: HalfMarathonsRoute,
  IndexDothtmlRoute: IndexDothtmlRoute,
  JuniorParkrunEventsRoute: JuniorParkrunEventsRoute,
  ListYourEventRoute: ListYourEventRoute,
  MarathonsRoute: MarathonsRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrailRunningEventsRoute: TrailRunningEventsRoute,
  UltraMarathonsRoute: UltraMarathonsRoute,
  AdminLoginRoute: AdminLoginRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EventsSlugRoute: EventsSlugRoute,
  ParkrunEventsSlugRoute: ParkrunEventsSlugRoute,
  RunningEventsSlugRoute: RunningEventsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  ParkrunEventsIndexRoute: ParkrunEventsIndexRoute,
  ApiPublicImportEventsRoute: ApiPublicImportEventsRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ParkrunEventsRegionRegionRoute: ParkrunEventsRegionRegionRoute,
  RunningEventsSlugDistanceRoute: RunningEventsSlugDistanceRoute,
  ApiPublicAdminFixEventUrlsRoute: ApiPublicAdminFixEventUrlsRoute,
  ApiPublicAdminSyncEnglandAthleticsRoute:
    ApiPublicAdminSyncEnglandAthleticsRoute,
  ApiPublicAdminSyncScottishAthleticsRoute:
    ApiPublicAdminSyncScottishAthleticsRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
