/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ListYourEventRouteImport } from './routes/list-your-event'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunningEventsSlugRouteImport } from './routes/running-events.$slug'
import { Route as ApiPublicImportEventsRouteImport } from './routes/api/public/import-events'
import { Route as ApiPublicAdminFixEventUrlsRouteImport } from './routes/api/public/admin/fix-event-urls'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ListYourEventRoute = ListYourEventRouteImport.update({
  id: '/list-your-event',
  path: '/list-your-event',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunningEventsSlugRoute = RunningEventsSlugRouteImport.update({
  id: '/running-events/$slug',
  path: '/running-events/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImportEventsRoute = ApiPublicImportEventsRouteImport.update({
  id: '/api/public/import-events',
  path: '/api/public/import-events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminFixEventUrlsRoute =
  ApiPublicAdminFixEventUrlsRouteImport.update({
    id: '/api/public/admin/fix-event-urls',
    path: '/api/public/admin/fix-event-urls',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list-your-event': typeof ListYourEventRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/running-events/$slug': typeof RunningEventsSlugRoute
  '/api/public/import-events': typeof ApiPublicImportEventsRoute
  '/api/public/admin/fix-event-urls': typeof ApiPublicAdminFixEventUrlsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list-your-event': typeof ListYourEventRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/running-events/$slug': typeof RunningEventsSlugRoute
  '/api/public/import-events': typeof ApiPublicImportEventsRoute
  '/api/public/admin/fix-event-urls': typeof ApiPublicAdminFixEventUrlsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/list-your-event': typeof ListYourEventRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/running-events/$slug': typeof RunningEventsSlugRoute
  '/api/public/import-events': typeof ApiPublicImportEventsRoute
  '/api/public/admin/fix-event-urls': typeof ApiPublicAdminFixEventUrlsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/list-your-event'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/running-events/$slug'
    | '/api/public/import-events'
    | '/api/public/admin/fix-event-urls'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/list-your-event'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/running-events/$slug'
    | '/api/public/import-events'
    | '/api/public/admin/fix-event-urls'
  id:
    | '__root__'
    | '/'
    | '/list-your-event'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/running-events/$slug'
    | '/api/public/import-events'
    | '/api/public/admin/fix-event-urls'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListYourEventRoute: typeof ListYourEventRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RunningEventsSlugRoute: typeof RunningEventsSlugRoute
  ApiPublicImportEventsRoute: typeof ApiPublicImportEventsRoute
  ApiPublicAdminFixEventUrlsRoute: typeof ApiPublicAdminFixEventUrlsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-your-event': {
      id: '/list-your-event'
      path: '/list-your-event'
      fullPath: '/list-your-event'
      preLoaderRoute: typeof ListYourEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/running-events/$slug': {
      id: '/running-events/$slug'
      path: '/running-events/$slug'
      fullPath: '/running-events/$slug'
      preLoaderRoute: typeof RunningEventsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/import-events': {
      id: '/api/public/import-events'
      path: '/api/public/import-events'
      fullPath: '/api/public/import-events'
      preLoaderRoute: typeof ApiPublicImportEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/fix-event-urls': {
      id: '/api/public/admin/fix-event-urls'
      path: '/api/public/admin/fix-event-urls'
      fullPath: '/api/public/admin/fix-event-urls'
      preLoaderRoute: typeof ApiPublicAdminFixEventUrlsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListYourEventRoute: ListYourEventRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RunningEventsSlugRoute: RunningEventsSlugRoute,
  ApiPublicImportEventsRoute: ApiPublicImportEventsRoute,
  ApiPublicAdminFixEventUrlsRoute: ApiPublicAdminFixEventUrlsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
